import { React, useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Capacete() {

  const [capacete21, setCapacete21] = useState(0);

  function capacete2para1(event) {
    const inputValue = event.target.value;
    let newValue;

    if(inputValue > 100 || inputValue <= 0) {
      newValue = -99999;
    } else if(inputValue >= 54) {
      newValue = 100;
    } else {
      newValue = Math.ceil(100 - 0.7*(55 - inputValue)) + 1;
    }
    setCapacete21(newValue);
  }

  return(
    <div className={styles.container}>
      <Head>
        <title>PUBG Calculator - Capacete</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1 className={styles.title}>
            Capacetes
          </h1>
          <Image src="/pubCapacete.jpeg" alt="PUBG Capacete" width={450} height={300} />
        </div>
      
        <div className={styles.marginT}>
          <div>
            <p className={styles.title}>
              Capacete 2 - Capacete 1
            </p>
            <input type="number" onChange={capacete2para1} />
            <div><span>{capacete21}</span></div>
          </div>
        </div>

         <div>
          <p className={styles.description}>
            Capacete 3 com qualquer vida é melhor que qualquer outro, pois tanka um HS
          </p>
         </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤ by &nbsp;</p>
        <a
          href="https://www.instagram.com/thiagorochatr/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Thiago Rocha
        </a>
      </footer>
    </div>
  )
}