import { React, useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Colete() {

  const [colete21, setColete21] = useState(0);
  const [colete32, setColete32] = useState(0);
  const [colete31, setColete31] = useState(0);

  function colete2para1(event) {
    const inputValue = event.target.value;
    let newValue;

    if(inputValue > 100 || inputValue <= 0) {
      newValue = -99999;
    } else if(inputValue >= 46) {
      newValue = 100;
    } else {
      newValue = 100 - (46 - inputValue);
    }
    setColete21(newValue);
  }

  function colete3para2(event) {
    const inputValue = event.target.value;
    let newValue;

    if(inputValue > 100 || inputValue <= 0) {
      newValue = -99999;
    } else if(inputValue >= 50) {
      newValue = 100;
    } else {
      newValue = 100 - (50 - inputValue);
    }
    setColete32(newValue);
  }

  function colete3para1(event) {
    const inputValue = event.target.value;
    let newValue, aux;

    if(inputValue > 100 || inputValue <= 0) {
      newValue = -99999;
    } else if(inputValue >= 50) {
      newValue = 100;
    } else {
      aux = 100 - (50 - inputValue); //99 até 51
      if(aux >= 46) {
        newValue = 100;
      } else {
        newValue = 100 - (46 - aux);
      }
    }
    setColete31(newValue);
  }

  return(
    <div className={styles.container}>
      <Head>
        <title>PUBG Calculator - Coletes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1 className={styles.title}>
            Coletes
          </h1>
          <Image src="/pubColete.jpeg" alt="PUBG Colete" width={500} height={400} />
        </div>
      
        <div className={styles.marginT}>
          <div>
            <p className={styles.title}>
              Colete 2 - Colete 1
            </p>
            <input type="number" onChange={colete2para1} />
            <div><span>{colete21}</span></div>
          </div>

          <div>
            <p className={styles.title}>
              Colete 3 - Colete 2
            </p>
            <input type="number" onChange={colete3para2} />
            <div><span>{colete32}</span></div>
          </div>
          
          <div>
            <p className={styles.title}>
              Colete 3 - Colete 1
            </p>
            <input type="number" onChange={colete3para1} />
            <div><span>{colete31}</span></div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤ by &nbsp;</p>
        <a
          href="https://www.instagram.com/thiagorochatr/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Thiago Rocha
        </a>
      </footer>
    </div>
  )
}