import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PUBG Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1 className={styles.title}>
            PUBG Calculator
          </h1>
          <Image src="/pubBG.jpg" alt="PUBG Background" width={700} height={450} />
        </div>

        <div className={styles.grid}>
          <a href="/queda" className={styles.card}>
            <h2>Quedas &rarr;</h2>
            <Image src="/pubParaquedas.jpeg" alt="PUBG Paraquedas" width={250} height={200} />
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Coletes &rarr;</h2>
            <Image src="/pubColete.jpeg" alt="PUBG Colete" width={250} height={200} />

          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>capacetes &rarr;</h2>
            <Image src="/pubCapacete.jpeg" alt="PUBG Capacete" width={250} height={200} />
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤ by &nbsp;</p>
        <a
          href="https://www.instagram.com/thiagorochatr/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Thiago Rocha
        </a>
      </footer>
    </div>
  )
}
