import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PUBG Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1 className={styles.title}>
            PUBG Calculator
          </h1>
          <Image src="/pubBG.jpg" alt="PUBG Background" width={700} height={450} />
        </div>

        <div className={styles.grid}>
          <Link href="/queda">
            <a className={styles.card}>
              <h2>Quedas &rarr;</h2>
              <Image src="/pubParaquedas.jpeg" alt="PUBG Paraquedas" width={250} height={200} />
            </a>
          </Link>

          <Link href="/colete">
            <a className={styles.card}>
              <h2>Coletes &rarr;</h2>
              <Image src="/pubColete.jpeg" alt="PUBG Colete" width={250} height={200} />
            </a>
          </Link>

          <Link href="/capacete">
            <a className={styles.card}>
              <h2>capacetes &rarr;</h2>
              <Image src="/pubCapacete.jpeg" alt="PUBG Capacete" width={250} height={200} />
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤ by &nbsp;</p>
        <a
          href="https://www.instagram.com/thiagorochatr/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Thiago Rocha
        </a>
      </footer>
    </div>
  )
}
