import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Queda() {
  return(
    <div className={styles.container}>
      <Head>
        <title>PUBG Calculator - Quedas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1 className={styles.title}>
            Quedas
          </h1>
          <Image src="/pubParaquedas2.jpg" alt="PUBG Paraquedas" width={700} height={400} />
        </div>

        <div className={styles.grid}>
          <p>Quadrado grande: </p>
          <Image src="/squareB.png" alt="PUBG Quadrado Grande" width={600} height={600}/>
          <p>Quadrado pequeno: </p>
          <Image src="/squareS.png" alt="PUBG Quadrado Penqueno" width={500} height={500}/>
        </div>
      
        <div>
          <p className={styles.title}>
            Erangel e Miramar
          </p>
          <div className={styles.grid}>
            <Image src="/erangel.jpg" alt="PUBG Erangel" width={250} height={250}/>
            <Image src="/miramar.jpg" alt="PUBG Miramar" width={250} height={250}/>
          </div>
          <p className={styles.description}>
            Pular em 950 m
            <br />
            <br />
            Mergulhar em 450 m
          </p>

          <p className={styles.title}>
            Sanhok
          </p>
          <p className={styles.description}>
            <Image src="/sanhok.jpg" alt="PUBG Sanhok" width={250} height={250}/>
            <br />
            <br />
            Pular em 1200 m
            <br />
            <br />
            Mergulhar em 350 - 400 m
          </p>

          <p className={styles.title}>
            Karakin
          </p>
          <p className={styles.description}>
            <Image src="/karakin.png" alt="PUBG Karakin" width={250} height={250}/>
            <br />
            <br />
            Pular em 350 m
            <br />
            <br />
            Mergulhar em 100 - 150 m de distância do alvo
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤ by &nbsp;</p>
        <a
          href="https://www.instagram.com/thiagorochatr/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Thiago Rocha
        </a>
      </footer>
    </div>
  )
}